### ISSUE TITLE
checking bindings into git

### ISSUE THREAD

**Issue by astraw** [jerry73204/apriltag-sys#1]
Hi, after writing my own bindings at https://github.com/strawlab/apriltag-sys, I discovered yours. Mine have a couple of differences from yours. One is that I run bindgen on one computer and check the result into git. This means I do not need to install bindgen and clang and other computers, which is nice. How would you feel about such an approach?

**Comment by jerry73204** [comment]
Definitely it is a great improvement. I would adopted the opencv-rust's approach: Use pre-built bindings in git, and leave additional feature to run bindgen.

Due to busy work hours in recent weeks, I might take weeks to check your work to merge into this crate. I think one way is to promote you as the co-author on crates.io, if you are willing to.

**Comment by astraw** [comment]
Thanks. I would be happy to update the approach in my version to be activated by a cargo feature. That's a good idea that does not require running a shell script thus more robust to different platforms, I think. I will work on an update to use a `buildtime-bindgen` feature based on the [opencv-rust approach](https://github.com/twistedfall/opencv-rust/blob/master/Cargo.toml).

(I will consolidate the following here, but could open other issues if you would like to track these separately - let me know.) In addition to the above point, the other changes I would do are to 1) use the `APRILTAG_SRC` environment variable, if it is set, to point to the April Tag source code if set and 2) if not, use pkg-config at build time to find the april tag library. I have tested these in my crate to work to automatically pick up the installed april tag library available with recent Debian releases, and this should work out of the box on other linuxes. You can check all this by using my existing crate linked above. This method still allows use of arbitrary locations of the april tags source without using pkg-config by using the environment variable, and has been pretty flexible and stable for me for the past few months of internal testing on several CPU architectures across a few debian-based linux distributions and on macOS.

I am happy to work to put these changes in place and publish a release if you agree and give me permission - on github and crates.io. I am also happy to put them in issues piecewise and make PRs for each of them. I check if the exported API maintain semver compatibility - which it hopefully will - and, if not, bump the release to 0.2.0.

**Comment by jerry73204** [comment]
You're invited as collaborator and I'll promote you soon.
I received issues from your mail. Let me reply to you later.

**Comment by astraw** [comment]
Great, thanks. I accepted the github invitation. Looking forward to your thoughts.

**Comment by jerry73204** [comment]
I browsed your [build.rs](https://github.com/strawlab/apriltag-sys/blob/master/build.rs). I see yours searches for C source files and compiles on the fly. There are two folds two this approach. It relieves users from compiling his own binary. That's the good part. However, it assumes the way the C source code is compiled, and may break on future updates of apriltag. Also, there is no way for user to add his own customizations (such as CFLAGS, LDFLAGS).

One possible improvement is that let's leave `APRILTAG_SRC` feature intact, and barely invoke cmake. I think it makes minimal assumptions on source, and let user customize his or her own `CMakeLists.txt`.

EDIT:
Other minor changes:
- Call bindgen in build.rs instead of script. By running the shell, it assumes `bindgen` in PATH.
- Add `rpath` if compiling from source. It prevents compiled binary linking apriltag provided system instead of user's.

**Comment by jerry73204** [comment]
I made an attempt to build with cmake, and encountered an [upstream bug](https://github.com/AprilRobotics/apriltag/pull/76). The cmake feature might be blocked until it's resolved.

**Comment by jerry73204** [comment]
@astraw I merged your work and now releases v0.1.2.
I sent an invitation mail to your public address (strawman at astraw dot com) on crates.io.
In order to make sure you're promoted, I kept v0.1.2 update from crates.io.
Please tell if you can run `cargo publish` successfully . Thanks.

BTW, there is an unpublished [apriltag-rust](https://github.com/jerry73204/apriltag-rust) serving high level API. Tell me if you would join as the developer.

**Comment by astraw** [comment]
Great, thanks!

So far, I don't have an email in my inbox (or spam folder) nor does the crates.io page for me at https://crates.io/me/pending-invites show anything. But the email you used should be correct. I'm not sure what is going on, let's wait a bit to see if the invite is just stuck in a queue somewhere.

Once I get that I'll try to publish as you suggest.

**Comment by jerry73204** [comment]
Tried again showing as the image. Maybe it comes in several minutes.
https://imgur.com/OhtcHoW

**Comment by astraw** [comment]
I think you may have to put in my github username. So "astraw" not the email address.

**Comment by astraw** [comment]
OK, great, I got the invite and published just now, so it works - thanks. I see now that the bindings are only built when the `buildtime-bindgen` feature is specified.

I have another issue which I will open or send as a PR. But this one is closed. Thanks again.
